repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=2048]
  - repo: local
    hooks:
      - id: stylish-haskell
        name: stylish-haskell
        entry: stylish-haskell --inplace
        language: haskell
        types: [haskell]
        additional_dependencies: [stylish-haskell]
        verbose: true
      - id: hlint
        name: hlint
        entry: hlint
        language: haskell
        types: [haskell]
        additional_dependencies: [hlint]
        verbose: true
      - id: build
        name: build
        entry: cabal build
        language: system
        verbose: true
        pass_filenames: false
      - id: test
        name: test
        entry: cabal test
        language: system
        verbose: true
        pass_filenames: false
      - id: format-cabal
        name: format-cabal
        entry: cabal format
        language: system
        verbose: true
        pass_filenames: false
